AWSTemplateFormatVersion: "2010-09-09"
Description: WAFv2 WebACL associated with ALB

Parameters:
  AlbArn:
    Type: String

Resources:

  WebACL:
    Type: AWS::WAFv2::WebACL
    Properties:
      Name: alb-webacl
      Scope: REGIONAL
      DefaultAction:
        Allow: {}
      VisibilityConfig:
        SampledRequestsEnabled: true
        CloudWatchMetricsEnabled: true
        MetricName: alb-webacl
      Rules:
        - Name: AWSManagedRulesCommonRuleSet
          Priority: 0
          OverrideAction:
            None: {}
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesCommonRuleSet
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: AWSManagedRulesCommonRuleSet

  WebACLAssociation:
    Type: AWS::WAFv2::WebACLAssociation
    Properties:
      ResourceArn: !Ref AlbArn
      WebACLArn: !GetAtt WebACL.Arn
